name: Bug Report
description: If you experience a bug in the Emulator, please open an issue here and fill out the template.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: 
  - 
body:
  - type: textarea
    id: what-should-happen
    attributes:
      label: Expected behavior?
      description: How was the emulator supposed to behave
      placeholder: Tell us what you expect to see!; use screenshots if necessary.
      value: 
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Actual behavior?
      description: Describe the issue you encountered.
      placeholder: Tell us what you see!; use screenshots if necessary.
      value: 
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce the problem
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
            1.
            2.
            3.
            4.
            5.
            ...
    validations:
      required: true
  - type: textarea
    id: error-messages
    attributes:
      label: Error messages?
      description: Was there an error message?
      placeholder: List any exception messages here!; use screenshots if necessary.
      value: 
    validations:
      required: true
