find_package(PkgConfig)

pkg_check_modules(GTK3 REQUIRED gtk+-3.0)
pkg_check_modules(GDK3 REQUIRED gdk-3.0)

set(GTK_INCLUDE_DIRS ${GTK3_INCLUDE_DIRS} ${GDK_INCLUDE_DIRS})
set(GTK_LIBRARY_DIRS ${GTK3_LIBRARY_DIRS} ${GDK_LIBRARY_DIRS})
set(GTK_LIBRARIES ${GTK3_LIBRARIES} ${GDK_LIBRARIES})
